#! /usr/bin/env python3
# -*- coding: utf-8 -*-

# pytrash file is part of pytrash
#
# pytrash - implementation of the "trash" for Slackware linux
# Home page: https://github.com/MyRequiem/pytrash
#
# Copyright (c) 2018 Vladimir MyRequiem Astrakhan, Russia
# <mrvladislavovich@gmail.com>
# All rights reserved
# See LICENSE for details.


import sys

from pytrash.main import Main


if __name__ == '__main__':
    sys.exit(Main().start())
